services:
  buildozer:
    build:
      context: .
      dockerfile: Dockerfile
    dns:
      - 8.8.8.8
    image: kivy-buildozer
    container_name: kivy-buildozer
    volumes:
      - ./:/app
      - .:/home/builduser/app
      - buildozer_cache:/home/builduser/app/.buildozer
    working_dir: /app
    tty: true
    stdin_open: true
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    networks:
      - my_network  # Define a custom network if needed

volumes:
  buildozer_cache:  # Define the named volume for caching

networks:
  my_network: # Define the custom network
